### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by borismassesa** [borismassesa/double_pendulum-simulation#5]
Develop a README file that outlines the project’s purpose, setup instructions, usage, and contribution guidelines. This serves as the main documentation for the project.

**Comment by borismassesa** [comment]
I have created the ReadMe file.

**Comment by Marwa-Alsalameh** [comment]
I have updated ReadMe

**Comment by borismassesa** [comment]
Completed this task, Boris, Marwa and Karan.

![Image](https://github.com/user-attachments/assets/207cc97f-6f43-4d0f-b150-f872f06c39fd)
