### ISSUE TITLE
Document Project Structure

### ISSUE THREAD

**Issue by borismassesa** [borismassesa/double_pendulum-simulation#6]
Provide documentation on the folder and file structure of the Godot project, helping team members understand where to add code, assets, and scenes.

**Comment by borismassesa** [comment]
I have assigned it to Karan.

**Comment by Marwa-Alsalameh** [comment]
COMP360_DoublePendulum/
src/
  - main.gd                # Main script with _physics_process for frame updates
  - pendulum.gd            # Script for pendulum motion calculations
assets/
   - pendulum_segment1.obj   # 3D model for pendulum’s first segment
   - pendulum_segment2.obj   # 3D model for pendulum’s second segment
docs/
   - README.md               # Main documentation and task breakdown
   - setup_instructions.md   # Detailed setup instructions
   - bug_log.md              # Bug log with images and descriptions
tests/
    - test_pendulum.gd        # Test script for verifying pendulum functionality
    - git_hooks/              # Directory for Git hook scripts (e.g., pre-commit tests)
README.md                   # Project overview, setup guide, and usage instructions


This is the project breakdown structure.
